/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ManipulaMatriz;

import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.TableColumn;

/**
 *
 * @author Alinda
 */
public class TelaMatriz extends javax.swing.JFrame {

    /**
     * Creates new form TelaMAtriz
     */
    private MatrizDeInteiros matriz;
    private TabelaModelo tabelaModelo;
    private Operacao estado;
    private int linha = 0;
    private int coluna = 0;

    public TelaMatriz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFLinhaMatriz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFColunaMatriz = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBDefinirMatriz = new javax.swing.JButton();
        jBGerarMatriz = new javax.swing.JButton();
        jBDiagonaPrincipal = new javax.swing.JButton();
        jBSomaLinhas = new javax.swing.JButton();
        jBSomaColunas = new javax.swing.JButton();
        jBTransposta = new javax.swing.JButton();
        jBDiagSecundaria = new javax.swing.JButton();
        jBBuscaValor = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBMediaColuna = new javax.swing.JButton();
        jBTroca1Linha = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operações com Matriz de Inteiros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordem da Matriz:"));

        jLabel1.setText("Linhas:");

        jLabel2.setText("Colunas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFLinhaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFColunaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFLinhaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFColunaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz:"));

        jTTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTTabela);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações:"));

        jBDefinirMatriz.setText("Definir Matriz");
        jBDefinirMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDefinirMatrizActionPerformed(evt);
            }
        });

        jBGerarMatriz.setText("Gerar Matriz");
        jBGerarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarMatrizActionPerformed(evt);
            }
        });

        jBDiagonaPrincipal.setText("Diag Principal");
        jBDiagonaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiagonaPrincipalActionPerformed(evt);
            }
        });

        jBSomaLinhas.setText("Soma linhas");
        jBSomaLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaLinhasActionPerformed(evt);
            }
        });

        jBSomaColunas.setText("Soma colunas");
        jBSomaColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaColunasActionPerformed(evt);
            }
        });

        jBTransposta.setText("Transposta");
        jBTransposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTranspostaActionPerformed(evt);
            }
        });

        jBDiagSecundaria.setText("Diag Secundaria");
        jBDiagSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiagSecundariaActionPerformed(evt);
            }
        });

        jBBuscaValor.setText("Busca Valor");
        jBBuscaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaValorActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBMediaColuna.setText("Media das colunas");
        jBMediaColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMediaColunaActionPerformed(evt);
            }
        });

        jBTroca1Linha.setText("Troca 1 linha");
        jBTroca1Linha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTroca1LinhaActionPerformed(evt);
            }
        });

        jButton2.setText("Produto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBuscaValor, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jBMediaColuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTroca1Linha, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jBTransposta, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jBDefinirMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGerarMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDiagonaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSomaColunas, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jBSomaLinhas, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jBDiagSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBBuscaValor, jBDefinirMatriz, jBDiagSecundaria, jBDiagonaPrincipal, jBGerarMatriz, jBLimpar, jBMediaColuna, jBSomaColunas, jBSomaLinhas, jBTransposta, jBTroca1Linha});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBDefinirMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGerarMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDiagonaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDiagSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSomaLinhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSomaColunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTransposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscaValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMediaColuna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTroca1Linha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBDefinirMatriz, jBDiagSecundaria, jBDiagonaPrincipal, jBGerarMatriz, jBSomaColunas, jBSomaLinhas, jBTransposta});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado:"));

        jTAResultado.setColumns(20);
        jTAResultado.setEditable(false);
        jTAResultado.setLineWrap(true);
        jTAResultado.setRows(5);
        jTAResultado.setTabSize(4);
        jTAResultado.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Operacao getEstado() {
        return estado;
    }

    /* Ação do botao de criar matriz*/
    private void jBDefinirMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDefinirMatrizActionPerformed
        /*checar se foi colcoado um valor valido no textbox de quantidades de linhas*/
        if (jTFLinhaMatriz.getText().trim().isEmpty() || Integer.parseInt(jTFLinhaMatriz.getText())<= 0) {
            JOptionPane.showMessageDialog(null,
                    "Informe um valor valido para linhas",
                    "Manipula Matriz", 0);
            jTFLinhaMatriz.setText("");
            jTFLinhaMatriz.requestFocus();
            return;
        }

        if (jTFColunaMatriz.getText().trim().isEmpty() || Integer.parseInt(jTFColunaMatriz.getText()) <= 0) {
            JOptionPane.showMessageDialog(null,
                    "Informe um valor valido para colunas",
                    "Manipula Matriz", 0);
            jTFColunaMatriz.setText("");
            jTFColunaMatriz.requestFocus();
            return;

        }
        
        linha = Integer.parseInt(jTFLinhaMatriz.getText());
        coluna = Integer.parseInt(jTFColunaMatriz.getText());

        matriz = new MatrizDeInteiros(linha, coluna);
        formataTabela();
        setEstado(Operacao.INICIALIZACAO);
    }//GEN-LAST:event_jBDefinirMatrizActionPerformed

    private void jBGerarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarMatrizActionPerformed
        matriz.setMatriz();
        formataTabela();
        setEstado(Operacao.OPERACAO);
    }//GEN-LAST:event_jBGerarMatrizActionPerformed

    private void jBDiagonaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiagonaPrincipalActionPerformed
        
    }//GEN-LAST:event_jBDiagonaPrincipalActionPerformed

    private void formataTabela() {
        tabelaModelo = new TabelaModelo(matriz.getMatriz());
        jTTabela.setModel(tabelaModelo);
        Cabecalho cabecalhoMatriz = new Cabecalho();
        TableColumn tc = jTTabela.getColumn("");
        tc.setCellRenderer(cabecalhoMatriz);
        jScrollPane1.setHorizontalScrollBar(new JScrollBar(0));
        jTTabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void jBSomaLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaLinhasActionPerformed
       
    }//GEN-LAST:event_jBSomaLinhasActionPerformed

    private void jBSomaColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaColunasActionPerformed
      
    }//GEN-LAST:event_jBSomaColunasActionPerformed

    private void jBDiagSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiagSecundariaActionPerformed
      
    }//GEN-LAST:event_jBDiagSecundariaActionPerformed

    private void jBTranspostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTranspostaActionPerformed
       
    }//GEN-LAST:event_jBTranspostaActionPerformed

    private void jBBuscaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaValorActionPerformed
      

    }//GEN-LAST:event_jBBuscaValorActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTAResultado.setText("");
        jTFLinhaMatriz.setText(null);
        jTFColunaMatriz.setText(null);
        tabelaModelo.excluiLinhasTabela();
        jTFLinhaMatriz.requestFocusInWindow();
        linha = 0;
        coluna = 0;
        setEstado(Operacao.CRIACAO);
    }//GEN-LAST:event_jBLimparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setEstado(Operacao.CRIACAO);
    }//GEN-LAST:event_formWindowOpened

    private void jBMediaColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMediaColunaActionPerformed
       
    }//GEN-LAST:event_jBMediaColunaActionPerformed

    private void jBTroca1LinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTroca1LinhaActionPerformed
      
    }//GEN-LAST:event_jBTroca1LinhaActionPerformed

    public void setEstado(Operacao estado) {
        this.estado = estado;
        if (estado == Operacao.CRIACAO) {
            jBDefinirMatriz.setEnabled(true);
            jBGerarMatriz.setEnabled(false);
            jBDiagonaPrincipal.setEnabled(false);
            jBDiagSecundaria.setEnabled(false);
            jBSomaLinhas.setEnabled(false);
            jBSomaColunas.setEnabled(false);
            jBTransposta.setEnabled(false);
            jBBuscaValor.setEnabled(false);
            jBLimpar.setEnabled(false);
        } else if (estado == Operacao.INICIALIZACAO) {
            jBGerarMatriz.setEnabled(linha >= 2 && coluna >= 2);
            jBDefinirMatriz.setEnabled(false);
            jBDiagonaPrincipal.setEnabled(false);
            jBDiagSecundaria.setEnabled(false);
            jBSomaLinhas.setEnabled(false);
            jBSomaColunas.setEnabled(false);
            jBTransposta.setEnabled(false);
            jBBuscaValor.setEnabled(false);
            jBLimpar.setEnabled(false);
        } else if (estado == Operacao.OPERACAO) {
            jBDefinirMatriz.setEnabled(false);
            jBGerarMatriz.setEnabled(linha >= 2 && coluna >= 2);
            jBDiagonaPrincipal.setEnabled(matriz.ehQuadrada());
            jBDiagSecundaria.setEnabled(matriz.ehQuadrada());
            jBSomaLinhas.setEnabled(linha >= 2 && coluna >= 2);
            jBSomaColunas.setEnabled(linha >= 2 && coluna >= 2);
            jBTransposta.setEnabled(linha >= 2 && coluna >= 2);
            jBBuscaValor.setEnabled(linha >= 2 && coluna >= 2);
            jBLimpar.setEnabled(linha >= 2 && coluna >= 2);
        }

    }

    /**
     * @param args the command line arguments"
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMatriz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscaValor;
    private javax.swing.JButton jBDefinirMatriz;
    private javax.swing.JButton jBDiagSecundaria;
    private javax.swing.JButton jBDiagonaPrincipal;
    private javax.swing.JButton jBGerarMatriz;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBMediaColuna;
    private javax.swing.JButton jBSomaColunas;
    private javax.swing.JButton jBSomaLinhas;
    private javax.swing.JButton jBTransposta;
    private javax.swing.JButton jBTroca1Linha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFColunaMatriz;
    private javax.swing.JTextField jTFLinhaMatriz;
    private javax.swing.JTable jTTabela;
    // End of variables declaration//GEN-END:variables
}
